### ISSUE TITLE
Weird Error code upon launch

### ISSUE THREAD

**Issue by shadowfire1217** [David20122/Sound-Space-Quantum-Editor#1]
![Screen Shot 2020-10-01 at 8 41 33 PM](https://user-images.githubusercontent.com/29960748/94885932-86b1ce00-0426-11eb-8f12-4b8690dae911.png)

**Comment by Avibah** [comment]
did you maybe try extracting the zip?
i dont know why people keep asking why this happens even though the exe literally cant read inside zip files

**Comment by shadowfire1217** [comment]
It was unzipped. It turns out I just needed to install the fonts it mentioned, as it couldn't install them for some reason

**Comment by krmeet** [comment]
you 100% are never required to install the fonts. you definitely didnt run the extracted editor when you got this error as it only happens when:
A) the editor is moved to a different folder or
B) you're trying to run it from the zip file

**Comment by shadowfire1217** [comment]
You sure bout that?
![Screen Shot 2020-10-02 at 1 15 35 AM](https://user-images.githubusercontent.com/29960748/94902319-cf7c7d80-044c-11eb-87e3-472c1efb5e9d.png)

**Comment by krmeet** [comment]
resolved
