### ISSUE TITLE
Song not working ingame.

### ISSUE THREAD

**Issue by Mortif3rum** [David20122/Sound-Space-Quantum-Editor#11]
Basically, I started making a map on the app. Then I was testing it in-game. And it was working. But not for my friend. When he tried it, it would say loading for a second then put him back on the menu. I'd really appreciate some help with this.

**Comment by Avibah** [comment]
Can you provide the map in question?

**Comment by Mortif3rum** [comment]
> Can you provide the map in question?

By this do you mean the map code or? Sorry, i literally started mapping today.

**Comment by Avibah** [comment]
Yes, the map code. You can upload it as a gist at gist.github.com and send the link for the raw data.

**Comment by Mortif3rum** [comment]
> Yes, the map code. You can upload it as a gist at gist.github.com and send the link for the raw data.

https://gist.githubusercontent.com/Mortif3rum/9df9101aba577652bc922be9056c6c21/raw/86ee9144416f6b08edaf4cb5f49fa2e3bd17a71c/Sound%2520Space%2520broken%2520song like this??

**Comment by Avibah** [comment]
Yep, exactly like that. The map works fine for me and I can't really find anything wrong with the map, are you sure you sent them the correct data and that they used that exact data? Also, that link can be loaded ingame so if you want to make sure it works with that you can.

**Comment by Mortif3rum** [comment]
> Yep, exactly like that. The map works fine for me and I can't really find anything wrong with the map, are you sure you sent them the correct data and that they used that exact data? Also, that link can be loaded ingame so if you want to make sure it works with that you can.

Yeah hes gonna try the link soon. He said he didnt copy the raw code wrong but u can rlly be sure 100% sure. Ty for the help anyway i appreciate how quickly you responded.
