### ISSUE TITLE
Does not load when I try and load it on linux.

### ISSUE THREAD

**Issue by Average-FNF-Fan** [David20122/Sound-Space-Quantum-Editor#20]
No window pops up, it doesn't even load. I checked my task manager and nothing about it was there.
I am using UBUNTU Linux 20.04.

**Comment by Avibah** [comment]
Did you get a crash report? It would be 'crash-report.txt' in the same directory as the editor.

**Comment by Average-FNF-Fan** [comment]
> Did you get a crash report? It would be 'crash-report.txt' in the same directory as the editor.

Nope, literally nothing happens. I launch it and just... nothing. No window, nothing.

**Comment by Average-FNF-Fan** [comment]
I can get some footage if you need

**Comment by Avibah** [comment]
Do you have the .NET 6.0 runtime installed? You'll need it to run SSQE if you don't already have it.
If you do, does it run when launched via the terminal?

**Comment by Average-FNF-Fan** [comment]
Nope, installing .NET 6.0 RN

**Comment by Average-FNF-Fan** [comment]
Nothing worked even after installing it. And I'm not sure how to launch a file through the terminal but I doubt it will work

**Comment by Avibah** [comment]
Try giving it a `.sh` file extension and then running it.

If you want to also try running it through the terminal, you simply need to type the path to the file and press enter, ex. `"./Sound Space Quantum Editor"`, after opening the terminal in the folder containing the editor.

**Comment by Average-FNF-Fan** [comment]
I am not sure how to add a .sh file extension, do I rename the file? and if so... when I did that, nothing happened aswell. Also... when I try and to "./Sound Space Quantum Editor" it says "bash: ./Sound: No such file or directory"

**Comment by Avibah** [comment]
Did you include quotation marks in the command?

And yes, adding a file extension is just renaming the file and including it at the end. If this worked, the icon of the file should've changed, possibly to an arrow with an underscore.

**Comment by Average-FNF-Fan** [comment]
> Did you include quotation marks in the command?
> 
> And yes, adding a file extension is just renaming the file and including it at the end. If this worked, the icon of the file should've changed, possibly to an arrow with an underscore.

I did not use the quotations, and like I said before, nothing happened when I tried launching it as a .sh file

**Comment by Avibah** [comment]
You'll need to include the quotation marks for it to recognize the full file name.

**Comment by Average-FNF-Fan** [comment]
Oh ok. If this doesn't work, I'll probably just wait for an update to drop.

**Comment by Average-FNF-Fan** [comment]
Didn't work, I'm closing this.

**Comment by Avibah** [comment]
I hear you got it to run with additional steps, so I have added them in a README in the current editor distribution. I'm hoping it'll help others in the future if they run into the same issue.
