### ISSUE TITLE
Backround.png isnt working

### ISSUE THREAD

**Issue by PlkaGithub** [David20122/Sound-Space-Quantum-Editor#3]
I cannot get backround.png to show up in the editor even tho i did all the steps!!!

**Comment by David20122** [comment]
Is it named "background.png" not "backround.png"

**Comment by PlkaGithub** [comment]
its named backround

**Comment by noobisnotbad** [comment]
Its supposed to be named background not backround

**Comment by krmeet** [comment]
this isn't a bug, this is your own fault for misspelling background
