### ISSUE TITLE
Editor Not Loading

### ISSUE THREAD

**Issue by silectobi4** [David20122/Sound-Space-Quantum-Editor#5]
The editor doesnt load aka it has an error that happens all the time and i just want to make a map for myself and a friend the errors message is: System.IO.FileNotFoundException: Couldn't find file ' assets/front 
etc. im to lazy to write it all now
<img width="959" alt="Unbenannt" src="https://user-images.githubusercontent.com/76253019/102690477-f35a8e80-4205-11eb-8363-491a79bbcb78.PNG">

**Comment by silectobi4** [comment]
And yes i extracted the file

**Comment by skipthevote** [comment]
well, i think you'll need to re download the editor, since the error says "main.ttf" is missing.

**Comment by silectobi4** [comment]
> well, i think you'll need to re download the editor, since the error says "main.ttf" is missing.

Im gonna try that thanks for the hint
