### ISSUE TITLE
doesn't work in the actual game

### ISSUE THREAD

**Issue by omrahm** [David20122/Sound-Space-Quantum-Editor#7]
when i paste the data into the game, it just shows a loading screen for 1 second and then returns me to the song menu. here is the song file, if that helps:
[werwerwer.txt](https://github.com/David20122/Sound-Space-Quantum-Editor/files/6175487/werwerwer.txt)

**Comment by PatrickkikALT** [comment]
![image](https://user-images.githubusercontent.com/45902985/111876915-1a5d6380-89a1-11eb-8f34-f88e366ea796.png)
you have a note after the end of the song delete that and it will work

**Comment by omrahm** [comment]
> ![image](https://user-images.githubusercontent.com/45902985/111876915-1a5d6380-89a1-11eb-8f34-f88e366ea796.png)
> you have a note after the end of the song delete that and it will work

thanks!
