### ISSUE TITLE
No .exe file

### ISSUE THREAD

**Issue by wtwmnpyaykam** [David20122/Sound-Space-Quantum-Editor#9]
Well I just searched for an application (.exe), and I didn't found it. Please, give me a lil' tutorial to find one.

**Comment by Avibah** [comment]
Download the latest version of SSQE from the Discord in #Quantum-Editor. You'll get the .exe file there.

**Comment by wtwmnpyaykam** [comment]
This is the latest version.

**Comment by Avibah** [comment]
Your antivirus may have deleted it then. Try restoring it and excluding it from scans.

**Comment by wtwmnpyaykam** [comment]
But it's disabled.

**Comment by Avibah** [comment]
Redownload then.
